### ISSUE TITLE
Probleme mit der styles.css

### ISSUE THREAD

**Issue by yoha-dev** [INF16A/kochbuch-frontend#33]
Die Styles.css überschreibt Bootstrap-CSS-Eigenschaften, weswegen verschiedene Elemente nicht mehr benutzt werden können. Beispielsweise kann ich keine Radiobuttons mehr verwenden, da sich diese dann überlagern und nicht mehr anklickbar sind. Siehe Foto. 

Eventuell ist es möglich, dass nicht Anpassungen für ein ganzes Element sondern Klassen dafür angelegt werden?  Vermutlich liegt es an label und input-selectoren. 
Mit Styles.css: 
![image](https://user-images.githubusercontent.com/31622712/32393190-debce40c-c0d8-11e7-9e55-6fa3e8d35e8b.png)
Ohne Styles.css: 
![image](https://user-images.githubusercontent.com/31622712/32393271-1c94fd46-c0d9-11e7-8df0-3a3df328cfcb.png)

Danke!

**Comment by hoernerth** [comment]
bereits bekannt - hätte auch nichts dagegen wenn jemand die CSS in die jeweiligen Komponenten auslagern würde oder die globalen Farben und Schriften auf SASS Ebene in Bootstrap ändern würde

**Comment by yoha-dev** [comment]
Wer hat denn die styles.css so verunstaltet? Bis sich Jemand anderes da eingelesen hat und versteht, was wofür ist, vergehen doch Wochen.

**Comment by hoernerth** [comment]
soweit ich das gesehen habe "gehört" die css zur Startseite

**Comment by hoernerth** [comment]
sollte gefixt sein !
