### ISSUE TITLE
Backend-Host in enviroment Datei auslagern

### ISSUE THREAD

**Issue by patrick246** [INF16A/kochbuch-frontend#79]
Um den Backend-Host nicht überall als localhost:8080 drin stehen zu haben, soll er in die enviroment-Dateien ausgelagert werden. Damit kann fürs Testen der Server lokal betrieben werden und im Produktivbetrieb auf die richtige Domain gelegt werden.

**Comment by ArmBeck16** [comment]
#99 resolved
